setwd("~/Desktop/R\ scripts\ MML/JAGS/minijags")
library(rjags)
library(R2jags)
d <- read.jagsdata("binary-data.R")
inits <- read.jagsdata("binary-init.R")
m <- jags.model("binary.bug", d, inits, n.chains=1)
update(m, 1000)
x <- coda.samples(m, "p", n.iter=10000)
plot(x)
summary(x)
